### ISSUE TITLE
Repository structure

### ISSUE THREAD

**Issue by IQAndreas** [photonstorm/Flixel-Power-Tools#12]
Just a few issues I have regarding the structure of the repository.

I can't seem to find the actual "code" for Flixel Power Tools other than in the pre-compressed ZIP (which defies the whole purpose of having version control, no? ;) This also makes forks or pull requests impossible.

Why are the Flixel libraries included? Do they have any changes made to them in order to work with some parts of the power tools? It may be easier including them as a SWC instead, but that's just a personal preference.

**Comment by michaelbartnett** [comment]
It's in `Flixel-Power-Tools/Test Suite/src/org/flixel/plugin/photonstorm`

I agree, it's kinda weird. Doesn't prevent me from setting things up how I want to, was just confusing having to dig down through all those directories to find the _real_ photonstorm folder.

**Comment by alteveer** [comment]
There is also no need to put a zip file in there, this link is that: https://github.com/photonstorm/Flixel-Power-Tools/downloads

I recommend moving that src/ dir to the root of your repo.
