### ISSUE TITLE
Package broken?

### ISSUE THREAD

**Issue by osro** [photonstorm/Flixel-Power-Tools#3]
Is the ZIP package somehow broken?

DropDownFX.as seems to be almost empty in zip file and it gives errors.
Also getting quite many other errors from missing greensock and other used libs as those are not included.

**Comment by osro** [comment]
Ok, seems like FlashBuilder 4.5 notices these errors much earlier than FlashDevelop which lets you build the project just fine if you don't use these few classes with missing libs.

**Comment by photonstorm** [comment]
The Test Suite uses greensock.swc which is in the lib folder - you'll need to link that in to your Flash Builder project or it won't compile.

DropDownFX is blank in master, yes, but working in the dev branch.

I compile with Strict fully enabled, so there shouldn't be any warnings that I don't see even using FlashDevelop, but if you've found some just let me know.

**Comment by osro** [comment]
1046: Type was not found or was not a compile-time constant: ModProcessor. FlxFlod.as /flixel/org/flixel/plugin/photonstorm line 42 Flex Problem

1118: Implicit coercion of a value with static type Object to a possibly unrelated type org.flixel:FlxSprite.   FlxSpecialFX.as /flixel/org/flixel/plugin/photonstorm   line 167    Flex Problem

1172: Definition neoart.flod could not be found.    FlxFlod.as  /flixel/org/flixel/plugin/photonstorm   line 15 Flex Problem

1180: Call to a possibly undefined method ModProcessor. FlxFlod.as  /flixel/org/flixel/plugin/photonstorm   line 63 Flex Problem

A file found in a source-path 'DropDownFX' must have the same name as the class definition inside the file 'DropDown'.  DropDownFX.as   /flixel/org/flixel/plugin/photonstorm/FX    Unknown Flex Problem

This is what FlashBuilder gives you straight when I unzip the "master" package to plugins directory.
By rudely deleting FlxSpecialFx, FlxFlod, DropDown files... FlashBuilder compiles it also fine.

On FlashDevelop wont give you these errores unless you use em somehow.
Example creating new FlxFlod will give same error as FlashBuilder gives straight.

**Comment by photonstorm** [comment]
The Getting Started guide in the Docs folder explains where to copy the Flod package and what it is.

**Comment by photonstorm** [comment]
Ok 1.6 Beta 1 is now up on the dev branch, and contains a lot of changes. You'll still need to copy the Flod package over though, but it should get rid of all errors listed above.

**Comment by osro** [comment]
Ah ok! :) I was reading the "Quick" instructions from the Github.
Maybe you could mention there as well that you need download flod & greensock from separated sources.

Example on my case it's much easier just delete those files than download the requirements.
Well, thanks for the replies and for awesome plugins!

**Comment by photonstorm** [comment]
Hmm you don't need to download them as they are in the Test Suite folder! Ahh wait, did you download JUST the photonstorm.zip file from github? Rather than the whole repository? That might explain it. Maybe I'll either put a readme into the zip file, or remove the zip file and force people to download the repo :)

**Comment by osro** [comment]
Ah... ofc! :D
 I thought that zip included the "full" package and Test Suite was just for show up.
I'll vote for forcing to download whole repo :D Makes update process much easier straight from GIT.
