### ISSUE TITLE
Shouldn't the flixel versions have their own fork?

### ISSUE THREAD

**Issue by xortive** [photonstorm/Flixel-Power-Tools#4]
should make merging in changes easier too.

**Comment by photonstorm** [comment]
Maybe, but I'm trying to keep the tools as independent of flixel as possible (without modifying the core if I can help it)

**Comment by xortive** [comment]
Can you make a change list, at least, to what you did to the modified version of flixel there?

**Comment by photonstorm** [comment]
Sure - but at the moment I've changed nothing. It's a bog standard 2.53 release.

**Comment by xortive** [comment]
oh, ok.
